spring:
  application:
    name: epik-boot3-api
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

#          kakao:
#            client-id: ${KAKAO_CLIENT_ID}
#            client-secret: ${KAKAO_CLIENT_SECRET}
#            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
#            authorization-grant-type: authorization_codec
#            client-authentication-method: client_secret_post
#            client-name: kakao
#            scope:
#              - profile_nickname
#              - account_email


  datasource:
    url: jdbc:h2:file:./data/testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # 테이블 자동 생성
    properties:
      hibernate:
        format_sql: true # SQL 보기 좋게 포맷팅
        show_sql: true # 로그에 하이버네이트가 생성한 쿼리문을 출력하는 옵션


  h2:
    console:
      enabled: true # H2 웹 콘솔 활성화
      path: /h2-console # H2 콘솔 접속 경로 설정
      settings:
        web-allow-others: true # 외부 접속 허용
        trace: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
      location: C:\\upload

  mail:
    host: smtp.gmail.com
    port: 587
    username: eun00864@gmail.com # 앱 비밀번호 발급받은 google 계정
    password: dhbtvdxabizvdrst # 발급받은 앱 비밀번호 (16자리 입니다.) -> 복붙
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  # 정적리소스 접근 경로 설정
  web:
    resources:
      static-locations: classpath:/static/
#      static-locations: file:../uploads/

epik:
  jwt:
    secret: "aBfnSNvv5P2JlSpFLxtPvsvSGI0/Rs0H9uqW3JwQ89GoGbGeCI41MD7PwvF1CyOmqH1+FchjH+pd0vpjtnr0Pg=="

server:
  servlet:
    context-path: /api/v1
  max-http-request-header-size: 8192
  port: 8081

file:
  tmp-dir: uploads/temp
  upload-dir: uploads/images